name: Code Style

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  php-cs-fixer:
    name: PHP CS Fixer (check)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run PHP CS Fixer (dry-run)
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --config=.php_cs.dist.php --allow-risky=yes --dry-run --diff
